name: Continuos Integration/Continuos Delivery

on:
  push:
    branches:
      - master

jobs:
  
  continuos-integration:
    
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone last version
        uses: actions/checkout@v4

      - name: Configure a Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm test
