name: Continuos Integration/Continuos Delivery

on:
  push:
    branches:
      - master

jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar la última versión del código
        uses: actions/checkout@v4

      - name: Configurar un entorno de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Instalar dependencias
        run: |
          npm install
          npm test

  continous-delivery:
    needs: continuos-integration
    runs-on: ubuntu-latest
    steps:
      - name: Deploy en el servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd BehanceProject/
            git pull origin master
            npm install --production
            pm2 restart src/index.js
